"""
Matthew Heitman - CS3C - Traveling Salesman Problem - Final Project

Traveling Salesman Problem - Held-Karp Algorithm

Finds the shortest possible round trip that starts at city 0, visits every
other city exactly once, and returns to city 0. Held-Karp solves this
exactly using dynamic programming: it solves every smaller version of the
problem once, stores the answer, and reuses it instead of recalculating
the same partial routes over and over (which is what brute force does).

Groups of cities are generated by hand below (combinations_of_size)
rather than using itertools.combinations, for the same reason brute
force's permutations are generated by hand: it's worth showing directly.
"""


def combinations_of_size(cities, size):
    """
    Yields every possible group of the given size, chosen from cities,
    with no regard to order - {1, 2} and {2, 1} count as the same group,
    so only one of them is yielded.

    The idea: for each city in turn, either include it in the group (and
    recursively choose the rest from everyone after it) or skip it
    entirely (and recursively choose the whole group from everyone
    after it). Only looking "after" the current city, never "before", is
    what keeps {1, 2} from also showing up as {2, 1}.
    """
    cities = list(cities)

    if size == 0:
        yield []
        return
    if size > len(cities):
        return

    first, rest = cities[0], cities[1:]

    # Groups that include "first":
    for smaller_group in combinations_of_size(rest, size - 1):
        yield [first] + smaller_group

    # Groups that skip "first" entirely:
    for group in combinations_of_size(rest, size):
        yield group


def held_karp(distances):
    """
    distances: a 2D list where distances[i][j] is the distance from city i
               to city j. City 0 is treated as the fixed starting city.

    Returns: (shortest_total_distance, optimal_route)
             optimal_route is a list of city numbers in the order visited,
             starting and ending at city 0.
    """
    number_of_cities = len(distances)
    other_cities = set(range(1, number_of_cities))  # every city except the start

    # Edge case: no other cities to visit, so the trip is just staying
    # home. Without this, the closing step below would crash trying to
    # find the cheapest "last city" out of an empty list of choices.
    if not other_cities:
        return 0, [0, 0]

    # cheapest_path_to[(visited_set, current_city)] holds the lowest cost of
    # a path that starts at city 0, visits exactly the cities in
    # visited_set, and ends up at current_city.
    cheapest_path_to = {}

    # came_from[(visited_set, current_city)] holds the city we must have
    # been at right before arriving at current_city, on the cheapest such
    # path. This lets us rebuild the actual route afterward, not just its
    # cost.
    came_from = {}

    # Base case: if we've visited only one city, there's only one way to
    # have gotten there - straight from the start.
    for city in other_cities:
        visited_set = frozenset({city})
        cheapest_path_to[(visited_set, city)] = distances[0][city]
        came_from[(visited_set, city)] = 0

    # Build up answers for larger and larger groups of visited cities,
    # always relying on answers already worked out for smaller groups.
    for group_size in range(2, len(other_cities) + 1):
        for group in combinations_of_size(other_cities, group_size):
            visited_set = frozenset(group)

            for current_city in visited_set:
                # To have arrived at current_city, we must have come from
                # some other city in this same group, after already having
                # visited everything else in the group.
                previously_visited = visited_set - {current_city}

                # Try every possible "city we just came from" and keep
                # whichever option is cheapest.
                best_cost, best_previous_city = min(
                    (cheapest_path_to[(previously_visited, previous_city)]
                     + distances[previous_city][current_city], previous_city)
                    for previous_city in previously_visited
                )

                cheapest_path_to[(visited_set, current_city)] = best_cost
                came_from[(visited_set, current_city)] = best_previous_city

    # Every other city has now been visited. Close the loop by returning to
    # city 0, trying each city as the last stop before heading back, and
    # keeping whichever choice gives the lowest total trip.
    all_visited = frozenset(other_cities)
    shortest_total_distance, last_city = min(
        (cheapest_path_to[(all_visited, city)] + distances[city][0], city)
        for city in other_cities
    )

    optimal_route = rebuild_route(came_from, all_visited, last_city)
    return shortest_total_distance, optimal_route


def rebuild_route(came_from, visited_set, current_city):
    """
    Walks backward through came_from to reconstruct the order cities were
    visited in, then reverses it so it reads start to finish.
    """
    route = [current_city]

    while True:
        previous_city = came_from[(visited_set, current_city)]
        if previous_city == 0:
            break
        visited_set = visited_set - {current_city}
        current_city = previous_city
        route.append(current_city)

    route.reverse()
    return [0] + route + [0]


if __name__ == "__main__":
    # The 4-city example we worked through by hand: cities 0-3 with
    # distances[i][j] = distance from city i to city j.
    distances = [
        [0, 10, 15, 20],
        [10, 0, 35, 25],
        [15, 35, 0, 30],
        [20, 25, 30, 0],
    ]

    total_distance, route = held_karp(distances)
    print("Shortest total distance:", total_distance)
    print("Optimal route:", route)
    # Expected: 80, with a tour ending at either city 1 or city 2 (both tie at 80)